// src/app/features/gestionnaire/pages/portefeuille/portefeuille.component.ts
import { Component } from '@angular/core';
import { LokComingSoonComponent } from '../../../../shared/components/lok-coming-soon/lok-coming-soon.component';

// Le portefeuille repose sur les mandats propriétaire → gestionnaire, une
// fonctionnalité prévue au plan produit (Phase 8) mais pas encore construite
// côté backend — voir audit /architect redesign propriétaire/gestionnaire,
// vague 2, 2026-07-28.
@Component({
  selector: 'app-portefeuille',
  standalone: true,
  imports: [LokComingSoonComponent],
  template: `
    <lok-coming-soon
      titre="Portefeuille"
      description="La délégation de biens par un propriétaire (mandats) est prévue mais pas encore disponible. Une fois construite, vous verrez ici tous les biens qui vous sont confiés."
      backRoute="/gestionnaire/dashboard"
    ></lok-coming-soon>
  `,
})
export class PortefeuilleComponent {}

// apps/frontend/src/app/gestionnaire/portefeuille/page.tsx
'use client';

import ComingSoon from '@/components/coming-soon';

// Le portefeuille repose sur les mandats propriétaire → gestionnaire, une
// fonctionnalité prévue au plan produit mais pas encore construite côté
// backend (module mandates, unité 31).
export default function PortefeuillePage() {
  return (
    <ComingSoon
      titre="Portefeuille"
      description="La délégation de biens par un propriétaire (mandats) est prévue mais pas encore disponible. Une fois construite, vous verrez ici tous les biens qui vous sont confiés."
      backRoute="/gestionnaire/dashboard"
    />
  );
}
