// src/app/features/biens/pages/bien-form/bien-form.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators, ReactiveFormsModule } from '@angular/forms';
import { Router, ActivatedRoute, RouterModule } from '@angular/router';
import { BiensService } from '../../services/biens.service';
import { DashboardService } from '../../../dashboard/services/dashboard.service';
import { invalidateCache } from '../../../../core/interceptors/http-cache.interceptor';
import { Bien, PropertyType, CreateBienRequest, PropertyPhoto } from '@core/models/bien.model';
import { LokUploadComponent, UploadedFile } from '../../../../shared/components/lok-upload/lok-upload.component';
import { LokAlerteComponent } from '../../../../shared/components/lok-alerte/lok-alerte.component';
import { LokSkeletonComponent } from '../../../../shared/components/lok-skeleton/lok-skeleton.component';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-bien-form',
  standalone: true,
  imports: [
    CommonModule,
    ReactiveFormsModule,
    RouterModule,
    LokUploadComponent,
    LokAlerteComponent,
    LokSkeletonComponent
  ],
  template: `
    <div class="min-h-screen bg-gray-50">
      <!-- Header -->
      <div class="bg-white border-b border-gray-200 px-6 py-4">
        <div class="flex items-center justify-between">
          <div>
            <h1 class="text-2xl font-bold text-gray-900">{{ isEditMode ? 'Modifier le bien' : 'Ajouter un bien' }}</h1>
            <p class="text-sm text-gray-600">{{ isEditMode ? 'Modifiez les informations du bien' : 'Remplissez les informations pour ajouter un nouveau bien' }}</p>
          </div>
          <button type="button" routerLink="/dashboard/biens" class="btn-secondary">Annuler</button>
        </div>
      </div>

      <!-- Contenu principal -->
      <div class="p-6 max-w-4xl mx-auto">
        <!-- Progression des étapes -->
        <div class="mb-8">
          <div class="flex items-center justify-between mb-4">
            @for (step of steps; track step.number) {
              <div class="flex items-center">
                <div
                  class="w-8 h-8 rounded-full flex items-center justify-center text-sm font-medium transition-colors"
                  [class]="currentStep >= step.number ? 'bg-blue-600 text-white' : 'bg-gray-200 text-gray-600'"
                >
                  @if (currentStep > step.number) {
                    <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7"/>
                    </svg>
                  } @else {
                    {{ step.number }}
                  }
                </div>
                @if (step.number < steps.length) {
                  <div class="w-16 h-1 mx-2 transition-colors" [class]="currentStep > step.number ? 'bg-blue-600' : 'bg-gray-200'"></div>
                }
              </div>
            }
          </div>
          <div class="flex justify-between text-xs text-gray-600">
            @for (step of steps; track step.number) {
              <span>{{ step.title }}</span>
            }
          </div>
        </div>


        <!-- Alerte d'erreur -->
        @if (errorMessage) {
          <lok-alerte type="error" [message]="errorMessage" class="mb-4 block"></lok-alerte>
        }

        <!-- Formulaire -->
        @if (loading) {
          <lok-skeleton type="card"></lok-skeleton>
        } @else {
          <form [formGroup]="bienForm" (ngSubmit)="onSubmit()" class="space-y-6">

            <!-- Étape 1 : Type et description -->
            @if (currentStep === 1) {
              <div class="bg-white rounded-xl p-6 shadow-sm border border-gray-100">
                <h2 class="text-lg font-semibold text-gray-900 mb-4">Type de bien</h2>
                <div class="space-y-4">
                  <div>
                    <label class="block text-sm font-medium text-gray-700 mb-2">Type de bien *</label>
                    <select formControlName="type" class="input-field">
                      <option value="">Sélectionnez un type</option>
                      <option value="VILLA">Villa</option>
                      <option value="APARTMENT">Appartement</option>
                      <option value="STUDIO">Studio</option>
                      <option value="COMMERCIAL">Local commercial / Bureau</option>
                    </select>
                    @if (bienForm.get('type')?.touched && bienForm.get('type')?.invalid) {
                      <p class="text-red-500 text-xs mt-1">Le type est requis</p>
                    }
                  </div>
                  <div>
                    <label class="block text-sm font-medium text-gray-700 mb-2">Description</label>
                    <textarea
                      formControlName="description"
                      class="input-field"
                      rows="4"
                      placeholder="Décrivez votre bien (optionnel)..."
                    ></textarea>
                  </div>
                </div>
              </div>
            }

            <!-- Étape 2 : Adresse -->
            @if (currentStep === 2) {
              <div class="bg-white rounded-xl p-6 shadow-sm border border-gray-100">
                <h2 class="text-lg font-semibold text-gray-900 mb-4">Adresse</h2>
                <div class="space-y-4">
                  <div>
                    <label class="block text-sm font-medium text-gray-700 mb-2">Quartier *</label>
                    <input
                      type="text"
                      formControlName="neighborhood"
                      class="input-field"
                      placeholder="Ex : Adewui, Bé, Tokoin…"
                    />
                    @if (bienForm.get('neighborhood')?.touched && bienForm.get('neighborhood')?.invalid) {
                      <p class="text-red-500 text-xs mt-1">Le quartier est requis</p>
                    }
                  </div>
                  <div>
                    <label class="block text-sm font-medium text-gray-700 mb-2">Ville *</label>
                    <select formControlName="city" class="input-field">
                      <option value="">Sélectionnez une ville</option>
                      <option>Lomé</option>
                      <option>Sokodé</option>
                      <option>Kara</option>
                      <option>Atakpamé</option>
                      <option>Kpalimé</option>
                      <option>Dapaong</option>
                      <option>Tsévié</option>
                      <option>Aného</option>
                    </select>
                    @if (bienForm.get('city')?.touched && bienForm.get('city')?.invalid) {
                      <p class="text-red-500 text-xs mt-1">La ville est requise</p>
                    }
                  </div>
                  <div>
                    <label class="block text-sm font-medium text-gray-700 mb-2">Adresse complète</label>
                    <input
                      type="text"
                      formControlName="address"
                      class="input-field"
                      placeholder="Ex : 12 Rue des Cocotiers, Lomé"
                    />
                  </div>
                </div>
              </div>
            }

            <!-- Étape 3 : Caractéristiques -->
            @if (currentStep === 3) {
              <div class="bg-white rounded-xl p-6 shadow-sm border border-gray-100">
                <h2 class="text-lg font-semibold text-gray-900 mb-4">Caractéristiques</h2>
                <div class="space-y-4">
                  <div>
                    <label class="block text-sm font-medium text-gray-700 mb-2">Surface (m²) *</label>
                    <input
                      type="number"
                      formControlName="surfaceArea"
                      class="input-field"
                      placeholder="Ex : 85"
                      min="1"
                    />
                    @if (bienForm.get('surfaceArea')?.touched && bienForm.get('surfaceArea')?.invalid) {
                      <p class="text-red-500 text-xs mt-1">La surface est requise (min. 1 m²)</p>
                    }
                  </div>
                  <div>
                    <label class="block text-sm font-medium text-gray-700 mb-2">Nombre de pièces</label>
                    <input
                      type="number"
                      formControlName="roomsCount"
                      class="input-field"
                      placeholder="Ex : 3"
                      min="1"
                    />
                  </div>
                  <div>
                    <label class="block text-sm font-medium text-gray-700 mb-2">Loyer mensuel (FCFA) *</label>
                    <input
                      type="number"
                      formControlName="monthlyRent"
                      class="input-field"
                      placeholder="Ex : 100 000"
                      min="1"
                    />
                    @if (bienForm.get('monthlyRent')?.touched && bienForm.get('monthlyRent')?.invalid) {
                      <p class="text-red-500 text-xs mt-1">Le loyer est requis</p>
                    }
                  </div>
                  <div>
                    <label class="block text-sm font-medium text-gray-700 mb-2">Charges mensuelles (FCFA)</label>
                    <input
                      type="number"
                      formControlName="monthlyCharges"
                      class="input-field"
                      placeholder="Ex : 15 000"
                      min="0"
                    />
                  </div>
                </div>
              </div>
            }

            <!-- Étape 4 : Photos -->
            @if (currentStep === 4) {
              <div class="bg-white rounded-xl p-6 shadow-sm border border-gray-100">
                <h2 class="text-lg font-semibold text-gray-900 mb-4">Photos</h2>

                <!-- Photos existantes (mode édition) -->
                @if (isEditMode && existingPhotos.length > 0) {
                  <div class="mb-5">
                    <p class="text-sm font-medium text-gray-700 mb-3">Photos actuelles</p>
                    <div class="grid grid-cols-3 gap-3 sm:grid-cols-4 md:grid-cols-5">
                      @for (photo of existingPhotos; track photo.id) {
                        <div class="relative aspect-square rounded-lg overflow-hidden border border-gray-200">
                          <img [src]="photo.url" alt="Photo du bien" class="w-full h-full object-cover">
                          <button
                            type="button"
                            (click)="supprimerPhoto(photo.id)"
                            [disabled]="deletingPhotoId === photo.id"
                            class="absolute top-1 right-1 w-7 h-7 bg-red-500 hover:bg-red-600 disabled:opacity-50 text-white rounded-full flex items-center justify-center shadow transition-colors"
                            title="Supprimer cette photo"
                          >
                            @if (deletingPhotoId === photo.id) {
                              <svg class="animate-spin w-3 h-3" fill="none" viewBox="0 0 24 24">
                                <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
                                <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z"></path>
                              </svg>
                            } @else {
                              <svg class="w-3 h-3" fill="none" stroke="currentColor" stroke-width="3" viewBox="0 0 24 24">
                                <path d="M18 6L6 18M6 6l12 12"/>
                              </svg>
                            }
                          </button>
                        </div>
                      }
                    </div>
                  </div>
                }

                @if (isEditMode && existingPhotos.length === 0 && !bienId) {
                  <p class="text-sm text-gray-500 mb-3">Vous pourrez ajouter des photos après la création.</p>
                } @else {
                  <p class="text-sm font-medium text-gray-700 mb-2">{{ isEditMode ? 'Ajouter de nouvelles photos' : 'Photos du bien' }}</p>
                  <lok-upload
                    accept="image/*"
                    [maxSize]="5"
                    [multiple]="true"
                    [maxFiles]="10"
                    (filesChange)="onPhotosChange($event)"
                  ></lok-upload>
                  <p class="text-xs text-gray-500 mt-2">JPG, PNG (max 5 Mo par photo, max 10 photos)</p>
                }
              </div>
            }

            <!-- Étape 5 : Documents -->
            @if (currentStep === 5) {
              <div class="bg-white rounded-xl p-6 shadow-sm border border-gray-100">
                <h2 class="text-lg font-semibold text-gray-900 mb-4">Documents</h2>
                <div class="space-y-6">
                  <div>
                    <label class="block text-sm font-medium text-gray-700 mb-2">État des lieux (PDF/Photos)</label>
                    <lok-upload
                      accept=".pdf,image/*"
                      [maxSize]="10"
                      [multiple]="true"
                      [maxFiles]="5"
                      (filesChange)="onEtatLieuxChange($event)"
                    ></lok-upload>
                  </div>
                  <div>
                    <label class="block text-sm font-medium text-gray-700 mb-2">Titre de propriété (PDF)</label>
                    <lok-upload
                      accept=".pdf"
                      [maxSize]="10"
                      [multiple]="false"
                      [maxFiles]="1"
                      (filesChange)="onTitreChange($event)"
                    ></lok-upload>
                  </div>
                  <div>
                    <label class="block text-sm font-medium text-gray-700 mb-2">Autres documents</label>
                    <lok-upload
                      accept=".pdf,.doc,.docx,image/*"
                      [maxSize]="10"
                      [multiple]="true"
                      [maxFiles]="5"
                      (filesChange)="onAutresDocumentsChange($event)"
                    ></lok-upload>
                  </div>
                </div>
              </div>
            }

            <!-- Navigation -->
            <div class="flex justify-between">
              <button
                type="button"
                (click)="previousStep()"
                [disabled]="currentStep === 1"
                class="btn-secondary"
                [class.opacity-50]="currentStep === 1"
              >
                Précédent
              </button>

              @if (currentStep < steps.length) {
                <button
                  type="button"
                  (click)="nextStep()"
                  [disabled]="!isCurrentStepValid()"
                  class="btn-primary"
                  [class.opacity-50]="!isCurrentStepValid()"
                >
                  Suivant
                </button>
              } @else {
                <button
                  type="submit"
                  [disabled]="bienForm.invalid || isSubmitting"
                  class="btn-primary"
                  [class.opacity-50]="bienForm.invalid || isSubmitting"
                >
                  @if (isSubmitting) {
                    <span class="flex items-center gap-2">
                      <svg class="animate-spin h-4 w-4" fill="none" viewBox="0 0 24 24">
                        <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
                        <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                      </svg>
                      Enregistrement…
                    </span>
                  } @else {
                    {{ isEditMode ? 'Enregistrer les modifications' : 'Créer le bien' }}
                  }
                </button>
              }
            </div>
          </form>
        }
      </div>
    </div>
  `,
})
export class BienFormComponent implements OnInit {
  bienForm: FormGroup;
  currentStep = 1;
  isEditMode = false;
  loading = false;
  isSubmitting = false;
  errorMessage = '';
  bienId: string | null = null;

  photoFiles: File[] = [];
  etatLieuxFiles: File[] = [];
  titreFiles: File[] = [];
  autresDocumentsFiles: File[] = [];
  existingPhotos: PropertyPhoto[] = [];
  deletingPhotoId: string | null = null;

  steps = [
    { number: 1, title: 'Type' },
    { number: 2, title: 'Adresse' },
    { number: 3, title: 'Loyer' },
    { number: 4, title: 'Photos' },
    { number: 5, title: 'Documents' },
  ];

  constructor(
    private fb: FormBuilder,
    private biensService: BiensService,
    private router: Router,
    private route: ActivatedRoute,
    private dashboardService: DashboardService,
  ) {
    this.bienForm = this.fb.group({
      type:           ['', Validators.required],
      description:    [''],
      neighborhood:   ['', Validators.required],
      city:           ['', Validators.required],
      address:        [''],
      surfaceArea:    ['', [Validators.required, Validators.min(1)]],
      roomsCount:     [null],
      monthlyRent:    ['', [Validators.required, Validators.min(1)]],
      monthlyCharges: [0, Validators.min(0)],
    });
  }

  ngOnInit(): void {
    this.bienId = this.route.snapshot.paramMap.get('id');
    if (this.bienId) {
      this.isEditMode = true;
      this.loadBien(this.bienId);
    }
  }

  loadBien(id: string): void {
    this.loading = true;
    this.biensService.getBienById(id).subscribe({
      next: (bien: Bien) => {
        this.bienForm.patchValue({
          type:           bien.type,
          description:    bien.description ?? '',
          neighborhood:   bien.neighborhood,
          city:           bien.city,
          address:        bien.address,
          surfaceArea:    bien.surfaceArea,
          roomsCount:     bien.roomsCount ?? null,
          monthlyRent:    bien.monthlyRent,
          monthlyCharges: bien.monthlyCharges,
        });
        this.existingPhotos = bien.photos ?? [];
        this.loading = false;
      },
      error: () => {
        this.errorMessage = 'Erreur lors du chargement du bien';
        this.loading = false;
      },
    });
  }

  nextStep(): void {
    if (this.currentStep < this.steps.length) this.currentStep++;
  }

  previousStep(): void {
    if (this.currentStep > 1) this.currentStep--;
  }

  isCurrentStepValid(): boolean {
    switch (this.currentStep) {
      case 1: return this.bienForm.get('type')?.valid ?? false;
      case 2: return (this.bienForm.get('neighborhood')?.valid ?? false) && (this.bienForm.get('city')?.valid ?? false);
      case 3: return (this.bienForm.get('surfaceArea')?.valid ?? false) && (this.bienForm.get('monthlyRent')?.valid ?? false);
      default: return true;
    }
  }

  onPhotosChange(files: UploadedFile[]): void {
    this.photoFiles = files.map((f) => f.file);
  }

  supprimerPhoto(photoId: string): void {
    if (!this.bienId || this.deletingPhotoId) return;
    this.deletingPhotoId = photoId;
    this.biensService.removePhoto(this.bienId, photoId).subscribe({
      next: () => {
        this.existingPhotos = this.existingPhotos.filter(p => p.id !== photoId);
        this.deletingPhotoId = null;
      },
      error: () => { this.deletingPhotoId = null; },
    });
  }

  onEtatLieuxChange(files: UploadedFile[]): void {
    this.etatLieuxFiles = files.map((f) => f.file);
  }

  onTitreChange(files: UploadedFile[]): void {
    this.titreFiles = files.map((f) => f.file);
  }

  onAutresDocumentsChange(files: UploadedFile[]): void {
    this.autresDocumentsFiles = files.map((f) => f.file);
  }

  onSubmit(): void {
    if (this.bienForm.invalid || this.isSubmitting) return;

    this.isSubmitting = true;
    this.errorMessage = '';

    const v = this.bienForm.value;
    const dto: CreateBienRequest = {
      type:           v.type as PropertyType,
      address:        v.address || `${v.neighborhood}, ${v.city}`,
      neighborhood:   v.neighborhood,
      city:           v.city,
      surfaceArea:    Number(v.surfaceArea),
      roomsCount:     v.roomsCount ? Number(v.roomsCount) : undefined,
      monthlyRent:    Number(v.monthlyRent),
      monthlyCharges: Number(v.monthlyCharges) || 0,
      description:    v.description || undefined,
    };

    if (this.isEditMode && this.bienId) {
      this.biensService.updateBien(this.bienId, dto).subscribe({
        next: () => this.uploadMedia(this.bienId!),
        error: (err: any) => this.handleError(err),
      });
    } else {
      this.biensService.createBien(dto).subscribe({
        next: (bien: Bien) => {
          this.uploadMedia(bien.id);
        },
        error: (err: any) => this.handleError(err),
      });
    }
  }

  private uploadMedia(bienId: string): void {
    const uploads: Promise<void>[] = [];

    if (this.photoFiles.length > 0) {
      uploads.push(
        new Promise<void>((res) =>
          this.biensService.addPhotos(bienId, this.photoFiles).subscribe({ next: () => res(), error: () => res() }),
        ),
      );
    }
    if (this.etatLieuxFiles.length > 0) {
      uploads.push(
        new Promise<void>((res) =>
          this.biensService.addDocuments(bienId, 'STATE_OF_PLAY', this.etatLieuxFiles).subscribe({ next: () => res(), error: () => res() }),
        ),
      );
    }
    if (this.titreFiles.length > 0) {
      uploads.push(
        new Promise<void>((res) =>
          this.biensService.addDocuments(bienId, 'PROPERTY_TITLE', this.titreFiles).subscribe({ next: () => res(), error: () => res() }),
        ),
      );
    }

    Promise.all(uploads).then(() => this.afterSave());
  }

  private afterSave(): void {
    this.isSubmitting = false;
    // Invalide le cache HTTP et le cache service pour que le dashboard
    // et la liste biens reflètent immédiatement le nouveau bien.
    invalidateCache('/dashboard');
    invalidateCache('/properties');
    this.dashboardService.invalidateCache();
    this.router.navigate(['/dashboard/biens']);
  }

  private handleError(err: any): void {
    this.isSubmitting = false;
    this.errorMessage = err.error?.message || 'Une erreur est survenue';
  }
}

// apps/frontend/src/app/dashboard/biens/_components/bien-form.tsx
'use client';

import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import Link from 'next/link';
import {
  propertiesApi,
  PROPERTY_TYPE_LABELS,
  type PropertyType,
  type PropertyPhoto,
} from '@/lib/properties';
import { ApiError } from '@/lib/api';
import { Dropdown } from '@/components/ui/dropdown';
import { FlowButton } from '@/components/ui/flow-button';
import './bien-form.css';

const VILLES = ['Lomé', 'Sokodé', 'Kara', 'Atakpamé', 'Kpalimé', 'Dapaong', 'Tsévié', 'Aného'];
const TYPE_OPTIONS = (Object.entries(PROPERTY_TYPE_LABELS) as [PropertyType, string][]).map(([value, label]) => ({ value, label }));
const VILLE_OPTIONS = VILLES.map((v) => ({ value: v, label: v }));

const STEPS = [
  { number: 1, title: 'Type' },
  { number: 2, title: 'Adresse' },
  { number: 3, title: 'Loyer' },
  { number: 4, title: 'Photos' },
];

interface FormState {
  type: PropertyType | '';
  description: string;
  neighborhood: string;
  city: string;
  address: string;
  surfaceArea: string;
  roomsCount: string;
  monthlyRent: string;
  monthlyCharges: string;
}

const EMPTY_FORM: FormState = {
  type: '',
  description: '',
  neighborhood: '',
  city: '',
  address: '',
  surfaceArea: '',
  roomsCount: '',
  monthlyRent: '',
  monthlyCharges: '',
};

export default function BienForm({ bienId }: { bienId?: string }) {
  const router = useRouter();
  const isEditMode = Boolean(bienId);

  const [form, setForm] = useState<FormState>(EMPTY_FORM);
  const [currentStep, setCurrentStep] = useState(1);
  const [loading, setLoading] = useState(isEditMode);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [errorMessage, setErrorMessage] = useState('');
  const [touched, setTouched] = useState<Record<string, boolean>>({});

  const [photoFiles, setPhotoFiles] = useState<File[]>([]);
  const [existingPhotos, setExistingPhotos] = useState<PropertyPhoto[]>([]);
  const [deletingPhotoId, setDeletingPhotoId] = useState<string | null>(null);

  useEffect(() => {
    if (!bienId) return;
    setLoading(true);
    propertiesApi
      .getById(bienId)
      .then((bien) => {
        setForm({
          type: bien.type,
          description: bien.description ?? '',
          neighborhood: bien.neighborhood,
          city: bien.city,
          address: bien.address,
          surfaceArea: String(bien.surfaceArea),
          roomsCount: bien.roomsCount != null ? String(bien.roomsCount) : '',
          monthlyRent: String(bien.monthlyRent),
          monthlyCharges: String(bien.monthlyCharges),
        });
        setExistingPhotos(bien.photos);
      })
      .catch((err) => {
        setErrorMessage(err instanceof ApiError ? err.message : 'Erreur lors du chargement du bien');
      })
      .finally(() => setLoading(false));
  }, [bienId]);

  const setField = (field: keyof FormState, value: string) => {
    setForm((f) => ({ ...f, [field]: value }));
  };

  const markTouched = (field: string) => setTouched((t) => ({ ...t, [field]: true }));

  const isStepValid = (step: number): boolean => {
    switch (step) {
      case 1:
        return form.type !== '';
      case 2:
        return form.neighborhood.trim() !== '' && form.city.trim() !== '';
      case 3:
        return Number(form.surfaceArea) >= 1 && Number(form.monthlyRent) >= 1;
      default:
        return true;
    }
  };

  const goNext = () => {
    if (isStepValid(currentStep) && currentStep < STEPS.length) setCurrentStep(currentStep + 1);
  };
  const goPrevious = () => {
    if (currentStep > 1) setCurrentStep(currentStep - 1);
  };

  const onPhotosSelected = (e: React.ChangeEvent<HTMLInputElement>) => {
    const files = Array.from(e.target.files ?? []);
    setPhotoFiles((prev) => [...prev, ...files].slice(0, 10));
    e.target.value = '';
  };

  const removeSelectedPhoto = (index: number) => {
    setPhotoFiles((prev) => prev.filter((_, i) => i !== index));
  };

  const removeExistingPhoto = async (photoId: string) => {
    if (!bienId || deletingPhotoId) return;
    setDeletingPhotoId(photoId);
    try {
      await propertiesApi.removePhoto(bienId, photoId);
      setExistingPhotos((prev) => prev.filter((p) => p.id !== photoId));
    } catch (err) {
      setErrorMessage(err instanceof ApiError ? err.message : 'Erreur lors de la suppression de la photo');
    } finally {
      setDeletingPhotoId(null);
    }
  };

  const onSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!isStepValid(1) || !isStepValid(2) || !isStepValid(3) || isSubmitting) return;

    setIsSubmitting(true);
    setErrorMessage('');

    const dto = {
      type: form.type as PropertyType,
      address: form.address.trim() || `${form.neighborhood}, ${form.city}`,
      neighborhood: form.neighborhood.trim(),
      city: form.city.trim(),
      surfaceArea: Number(form.surfaceArea),
      roomsCount: form.roomsCount ? Number(form.roomsCount) : undefined,
      monthlyRent: Number(form.monthlyRent),
      monthlyCharges: form.monthlyCharges ? Number(form.monthlyCharges) : 0,
      description: form.description.trim() || undefined,
    };

    try {
      const bien = isEditMode && bienId
        ? await propertiesApi.update(bienId, dto)
        : await propertiesApi.create(dto);

      if (photoFiles.length > 0) {
        await propertiesApi.addPhotos(bien.id, photoFiles).catch(() => {});
      }

      router.push(isEditMode ? `/dashboard/biens/${bien.id}` : '/dashboard/biens');
    } catch (err) {
      setErrorMessage(err instanceof ApiError ? err.message : 'Une erreur est survenue');
      setIsSubmitting(false);
    }
  };

  if (loading) {
    return (
      <div className="bf-page">
        <div className="bf-skeleton" />
      </div>
    );
  }

  return (
    <div className="bf-page">
      <div className="bf-header">
        <div>
          <h1 className="bf-title">{isEditMode ? 'Modifier le bien' : 'Ajouter un bien'}</h1>
          <p className="bf-subtitle">
            {isEditMode ? 'Modifiez les informations du bien' : 'Remplissez les informations pour ajouter un nouveau bien'}
          </p>
        </div>
        <Link href="/dashboard/biens" className="bf-btn-secondary">Annuler</Link>
      </div>

      <div className="bf-stepper">
        {STEPS.map((step) => (
          <div key={step.number} className="bf-step-wrap">
            <div className={`bf-step-dot${currentStep >= step.number ? ' active' : ''}`}>
              {currentStep > step.number ? '✓' : step.number}
            </div>
            <span className="bf-step-label">{step.title}</span>
          </div>
        ))}
      </div>

      {errorMessage && <div className="bf-alert-error">{errorMessage}</div>}

      <form onSubmit={onSubmit} className="bf-form">
        {currentStep === 1 && (
          <div className="bf-card">
            <h2 className="bf-card-title">Type de bien</h2>
            <div className="bf-field">
              <label htmlFor="bf-type">Type de bien *</label>
              <Dropdown
                id="bf-type"
                value={form.type}
                onChange={(v) => { setField('type', v); markTouched('type'); }}
                options={TYPE_OPTIONS}
                placeholder="Sélectionnez un type"
              />
              {touched.type && form.type === '' && <p className="bf-field-error">Le type est requis</p>}
            </div>
            <div className="bf-field">
              <label htmlFor="bf-description">Description</label>
              <textarea
                id="bf-description"
                rows={4}
                placeholder="Décrivez votre bien (optionnel)…"
                value={form.description}
                onChange={(e) => setField('description', e.target.value)}
                maxLength={2000}
              />
            </div>
          </div>
        )}

        {currentStep === 2 && (
          <div className="bf-card">
            <h2 className="bf-card-title">Adresse</h2>
            <div className="bf-field">
              <label htmlFor="bf-neighborhood">Quartier *</label>
              <input
                id="bf-neighborhood"
                type="text"
                placeholder="Ex : Adewui, Bé, Tokoin…"
                value={form.neighborhood}
                onChange={(e) => setField('neighborhood', e.target.value)}
                onBlur={() => markTouched('neighborhood')}
                maxLength={200}
              />
              {touched.neighborhood && form.neighborhood.trim() === '' && <p className="bf-field-error">Le quartier est requis</p>}
            </div>
            <div className="bf-field">
              <label htmlFor="bf-city">Ville *</label>
              <Dropdown
                id="bf-city"
                value={form.city}
                onChange={(v) => { setField('city', v); markTouched('city'); }}
                options={VILLE_OPTIONS}
                placeholder="Sélectionnez une ville"
              />
              {touched.city && form.city.trim() === '' && <p className="bf-field-error">La ville est requise</p>}
            </div>
            <div className="bf-field">
              <label htmlFor="bf-address">Adresse complète</label>
              <input
                id="bf-address"
                type="text"
                placeholder="Ex : 12 Rue des Cocotiers, Lomé"
                value={form.address}
                onChange={(e) => setField('address', e.target.value)}
                maxLength={200}
              />
            </div>
          </div>
        )}

        {currentStep === 3 && (
          <div className="bf-card">
            <h2 className="bf-card-title">Caractéristiques</h2>
            <div className="bf-field">
              <label htmlFor="bf-surface">Surface (m²) *</label>
              <input
                id="bf-surface"
                type="number"
                min={1}
                step="any"
                placeholder="Ex : 85"
                value={form.surfaceArea}
                onChange={(e) => setField('surfaceArea', e.target.value)}
                onBlur={() => markTouched('surfaceArea')}
              />
              {touched.surfaceArea && Number(form.surfaceArea) < 1 && <p className="bf-field-error">La surface est requise (min. 1 m²)</p>}
            </div>
            <div className="bf-field">
              <label htmlFor="bf-rooms">Nombre de pièces</label>
              <input id="bf-rooms" type="number" min={1} placeholder="Ex : 3" value={form.roomsCount} onChange={(e) => setField('roomsCount', e.target.value)} />
            </div>
            <div className="bf-field">
              <label htmlFor="bf-rent">Loyer mensuel (FCFA) *</label>
              <input
                id="bf-rent"
                type="number"
                min={1}
                placeholder="Ex : 100 000"
                value={form.monthlyRent}
                onChange={(e) => setField('monthlyRent', e.target.value)}
                onBlur={() => markTouched('monthlyRent')}
              />
              {touched.monthlyRent && Number(form.monthlyRent) < 1 && <p className="bf-field-error">Le loyer est requis</p>}
            </div>
            <div className="bf-field">
              <label htmlFor="bf-charges">Charges mensuelles (FCFA)</label>
              <input id="bf-charges" type="number" min={0} placeholder="Ex : 15 000" value={form.monthlyCharges} onChange={(e) => setField('monthlyCharges', e.target.value)} />
            </div>
          </div>
        )}

        {currentStep === 4 && (
          <div className="bf-card">
            <h2 className="bf-card-title">Photos</h2>

            {existingPhotos.length > 0 && (
              <div className="bf-photos-existing">
                <p className="bf-photos-label">Photos actuelles</p>
                <div className="bf-photos-grid">
                  {existingPhotos.map((photo) => (
                    <div key={photo.id} className="bf-photo-thumb">
                      <img src={photo.url} alt="" />
                      <button
                        type="button"
                        className="bf-photo-remove"
                        disabled={deletingPhotoId === photo.id}
                        onClick={() => removeExistingPhoto(photo.id)}
                        aria-label="Supprimer cette photo"
                      >
                        ×
                      </button>
                    </div>
                  ))}
                </div>
              </div>
            )}

            <p className="bf-photos-label">{isEditMode ? 'Ajouter de nouvelles photos' : 'Photos du bien'}</p>
            <label className="bf-upload-zone">
              <input type="file" accept="image/*" multiple onChange={onPhotosSelected} hidden />
              <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5"><path d="M21 15v4a2 2 0 01-2 2H5a2 2 0 01-2-2v-4" /><polyline points="17 8 12 3 7 8" /><line x1="12" y1="3" x2="12" y2="15" /></svg>
              <span>Cliquez pour choisir des photos</span>
            </label>
            <p className="bf-photos-hint">JPG, PNG (max 5 Mo par photo, max 10 photos)</p>

            {photoFiles.length > 0 && (
              <div className="bf-photos-grid">
                {photoFiles.map((file, i) => (
                  <div key={`${file.name}-${i}`} className="bf-photo-thumb">
                    <img src={URL.createObjectURL(file)} alt="" />
                    <button type="button" className="bf-photo-remove" onClick={() => removeSelectedPhoto(i)} aria-label="Retirer cette photo">×</button>
                  </div>
                ))}
              </div>
            )}
          </div>
        )}

        <div className="bf-nav">
          <button type="button" className="bf-btn-secondary" onClick={goPrevious} disabled={currentStep === 1}>Précédent</button>
          {currentStep < STEPS.length ? (
            <button key="next" type="button" className="bf-btn-primary" onClick={goNext} disabled={!isStepValid(currentStep)}>Suivant</button>
          ) : (
            <FlowButton
              key="submit"
              type="submit"
              disabled={isSubmitting}
              text={isSubmitting ? 'Enregistrement…' : isEditMode ? 'Enregistrer les modifications' : 'Créer le bien'}
            />
          )}
        </div>
      </form>
    </div>
  );
}
