// src/app/features/auth/pages/register/register.component.ts
import { Component, ChangeDetectionStrategy, ChangeDetectorRef, signal } from '@angular/core';
import { FormBuilder, FormGroup, Validators, ReactiveFormsModule } from '@angular/forms';
import { Router, RouterModule } from '@angular/router';
import { CommonModule } from '@angular/common';
import { AuthService } from '../../../../core/services/auth.service';

type Role = 'OWNER' | 'MANAGER';
type Step = 'role' | 'info' | 'cni' | 'success';

@Component({
  selector: 'app-register',
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule, RouterModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div class="register-page">
      <!-- Panneau gauche -->
      <div class="left-panel">
        <div class="left-content">
          <img src="/assets/WARAH-logo.png" alt="WARAH" class="logo">
          <h1>L'immobilier togolais<br>dans votre poche</h1>
          <div class="features">
            <div class="feature"><span class="dot"></span>Gérez vos biens à distance</div>
            <div class="feature"><span class="dot"></span>Encaissez via T-Money & Flooz</div>
            <div class="feature"><span class="dot"></span>Statistiques en temps réel</div>
            <div class="feature"><span class="dot"></span>Vérification CNI sécurisée</div>
          </div>
          <!-- Indicateur d'étapes -->
          <div class="steps-indicator">
            <div class="step-item" [class.active]="step() === 'role'" [class.done]="stepIndex() > 0">
              <span class="step-num">1</span><span>Rôle</span>
            </div>
            <div class="step-line"></div>
            <div class="step-item" [class.active]="step() === 'info'" [class.done]="stepIndex() > 1">
              <span class="step-num">2</span><span>Informations</span>
            </div>
            <div class="step-line"></div>
            <div class="step-item" [class.active]="step() === 'cni'" [class.done]="stepIndex() > 2">
              <span class="step-num">3</span><span>Pièce d'identité</span>
            </div>
          </div>
        </div>
      </div>

      <!-- Panneau droit -->
      <div class="right-panel">
        <div class="form-card">

          <!-- ÉTAPE 1 : Choix du rôle -->
          @if (step() === 'role') {
            <div class="step-content">
              <h2>Créer votre compte</h2>
              <p class="subtitle">Je suis…</p>
              <div class="role-grid">
                <button type="button" class="role-card" [class.selected]="selectedRole() === 'OWNER'" (click)="selectRole('OWNER')">
                  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5">
                    <path d="M3 9l9-7 9 7v11a2 2 0 01-2 2H5a2 2 0 01-2-2z"/>
                    <polyline points="9 22 9 12 15 12 15 22"/>
                  </svg>
                  <strong>Propriétaire</strong>
                  <span>Je possède des biens immobiliers au Togo</span>
                </button>
                <button type="button" class="role-card" [class.selected]="selectedRole() === 'MANAGER'" (click)="selectRole('MANAGER')">
                  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5">
                    <path d="M17 21v-2a4 4 0 00-4-4H5a4 4 0 00-4 4v2"/>
                    <circle cx="9" cy="7" r="4"/>
                    <path d="M23 21v-2a4 4 0 00-3-3.87M16 3.13a4 4 0 010 7.75"/>
                  </svg>
                  <strong>Gestionnaire</strong>
                  <span>Je gère des biens pour le compte de propriétaires</span>
                </button>
              </div>
              <button class="btn-primary" [disabled]="!selectedRole()" (click)="goToInfo()">
                Continuer
                <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M5 12h14M12 5l7 7-7 7"/></svg>
              </button>
              <p class="login-link">Déjà un compte ? <a routerLink="/auth/login">Se connecter</a></p>
            </div>
          }

          <!-- ÉTAPE 2 : Informations personnelles -->
          @if (step() === 'info') {
            <div class="step-content">
              <button class="back-btn" (click)="goBack()">← Retour</button>
              <h2>Vos informations</h2>
              <p class="subtitle">{{ selectedRole() === 'OWNER' ? 'Compte propriétaire' : 'Compte gestionnaire immobilier' }}</p>
              <form [formGroup]="infoForm" (ngSubmit)="goToCni()" class="form-fields">
                <div class="field-row">
                  <div class="field">
                    <label>Prénom *</label>
                    <input formControlName="firstName" type="text" placeholder="Kofi">
                    @if (infoForm.get('firstName')?.touched && infoForm.get('firstName')?.invalid) {
                      <span class="error">Prénom requis</span>
                    }
                  </div>
                  <div class="field">
                    <label>Nom *</label>
                    <input formControlName="lastName" type="text" placeholder="Mensah">
                    @if (infoForm.get('lastName')?.touched && infoForm.get('lastName')?.invalid) {
                      <span class="error">Nom requis</span>
                    }
                  </div>
                </div>
                <div class="field">
                  <label>Email *</label>
                  <input formControlName="email" type="email" placeholder="kofi@exemple.com">
                  @if (infoForm.get('email')?.touched && infoForm.get('email')?.invalid) {
                    <span class="error">Email valide requis</span>
                  }
                </div>
                <div class="field">
                  <label>Mot de passe * <small>(min 6 caractères)</small></label>
                  <input formControlName="password" type="password" placeholder="••••••••">
                  @if (infoForm.get('password')?.touched && infoForm.get('password')?.invalid) {
                    <span class="error">Minimum 6 caractères</span>
                  }
                </div>
                @if (selectedRole() === 'OWNER') {
                  <div class="field">
                    <label>Pays de résidence *</label>
                    <select formControlName="residenceCountry">
                      <option value="">Sélectionner…</option>
                      <option value="TG">Togo</option>
                      <option value="FR">France</option>
                      <option value="BE">Belgique</option>
                      <option value="CI">Côte d'Ivoire</option>
                      <option value="GH">Ghana</option>
                      <option value="SN">Sénégal</option>
                      <option value="US">États-Unis</option>
                      <option value="CA">Canada</option>
                      <option value="DE">Allemagne</option>
                      <option value="OTHER">Autre</option>
                    </select>
                    @if (infoForm.get('residenceCountry')?.touched && infoForm.get('residenceCountry')?.invalid) {
                      <span class="error">Pays requis</span>
                    }
                  </div>
                }
                <button type="submit" class="btn-primary" [disabled]="infoForm.invalid">
                  Continuer
                  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M5 12h14M12 5l7 7-7 7"/></svg>
                </button>
              </form>
            </div>
          }

          <!-- ÉTAPE 3 : CNI upload -->
          @if (step() === 'cni') {
            <div class="step-content">
              <button class="back-btn" (click)="step.set('info')">← Retour</button>
              <h2>Pièce d'identité</h2>
              <p class="subtitle">CNI en cours de validité — recto et verso (JPG/PNG, max 5 Mo)</p>

              @if (errorMessage()) {
                <div class="error-banner">{{ errorMessage() }}</div>
              }

              <div class="cni-grid">
                <!-- Recto -->
                <div class="upload-zone" [class.has-file]="cniRecto" (click)="triggerInput(rectInput)">
                  <input #rectInput type="file" accept="image/jpeg,image/png,image/webp" (change)="onFile($event, 'recto')" style="display:none">
                  @if (cniRecto) {
                    <div class="file-preview">
                      <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M9 11l3 3L22 4"/><path d="M21 12v7a2 2 0 01-2 2H5a2 2 0 01-2-2V5a2 2 0 012-2h11"/></svg>
                      <span>{{ cniRecto.name }}</span>
                    </div>
                  } @else {
                    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><path d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-8l-4-4m0 0L8 8m4-4v12"/></svg>
                    <strong>CNI Recto</strong>
                    <span>Cliquer pour sélectionner</span>
                  }
                </div>
                <!-- Verso -->
                <div class="upload-zone" [class.has-file]="cniVerso" (click)="triggerInput(versoInput)">
                  <input #versoInput type="file" accept="image/jpeg,image/png,image/webp" (change)="onFile($event, 'verso')" style="display:none">
                  @if (cniVerso) {
                    <div class="file-preview">
                      <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M9 11l3 3L22 4"/><path d="M21 12v7a2 2 0 01-2 2H5a2 2 0 01-2-2V5a2 2 0 012-2h11"/></svg>
                      <span>{{ cniVerso.name }}</span>
                    </div>
                  } @else {
                    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><path d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-8l-4-4m0 0L8 8m4-4v12"/></svg>
                    <strong>CNI Verso</strong>
                    <span>Cliquer pour sélectionner</span>
                  }
                </div>
              </div>

              @if (selectedRole() === 'MANAGER') {
                <div class="field" style="margin-top:1rem">
                  <label>Références professionnelles <small>(optionnel — max 5 fichiers)</small></label>
                  <input type="file" accept="image/*,.pdf" multiple (change)="onRefDocs($event)"
                    style="width:100%;padding:.5rem;border:1px dashed #d1d5db;border-radius:.5rem;cursor:pointer">
                  @if (refDocs.length > 0) {
                    <span class="text-sm text-gray-500">{{ refDocs.length }} fichier(s) sélectionné(s)</span>
                  }
                </div>
              }

              <button class="btn-primary" [disabled]="!cniRecto || !cniVerso || isLoading()" (click)="submit()">
                @if (isLoading()) {
                  <svg class="spinner" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="10" opacity=".25"/><path d="M12 2a10 10 0 0110 10" opacity=".75"/></svg>
                  Création en cours…
                } @else {
                  Créer mon compte
                }
              </button>
            </div>
          }

          <!-- ÉTAPE 4 : Succès -->
          @if (step() === 'success') {
            <div class="step-content success-content">
              <div class="success-icon">
                <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                  <circle cx="12" cy="12" r="10"/>
                  <path d="M9 12l2 2 4-4"/>
                </svg>
              </div>
              <h2>Compte créé !</h2>
              <p>Votre compte a été créé avec succès. Votre pièce d'identité est en cours de vérification (sous 24h).</p>
              <p class="info-note">Vous pouvez vous connecter dès maintenant. Certaines fonctionnalités seront disponibles après validation de votre CNI.</p>
              <a routerLink="/auth/login" class="btn-primary">Se connecter</a>
            </div>
          }

        </div>
      </div>
    </div>
  `,
  styles: [`
    .register-page {
      display: flex;
      min-height: 100vh;
      font-family: system-ui, -apple-system, sans-serif;
    }

    /* Panneau gauche */
    .left-panel {
      width: 42%;
      background: linear-gradient(135deg, #0A2650 0%, #0F4C81 60%, #081E41 100%);
      display: flex;
      align-items: center;
      justify-content: center;
      padding: 2rem;
      position: sticky;
      top: 0;
      height: 100vh;
    }
    @media (max-width: 768px) { .left-panel { display: none; } }

    .left-content { color: white; max-width: 360px; }
    .logo { height: 64px; object-fit: contain; mix-blend-mode: lighten; margin-bottom: 2rem; }
    .left-content h1 { font-size: 1.75rem; font-weight: 700; line-height: 1.3; margin-bottom: 2rem; }

    .features { margin-bottom: 2.5rem; display: flex; flex-direction: column; gap: .75rem; }
    .feature { display: flex; align-items: center; gap: .75rem; font-size: .95rem; opacity: .9; }
    .dot { width: 8px; height: 8px; background: #C9982E; border-radius: 50%; flex-shrink: 0; }

    .steps-indicator { display: flex; align-items: center; gap: .5rem; }
    .step-item { display: flex; align-items: center; gap: .5rem; font-size: .8rem; opacity: .5; }
    .step-item.active { opacity: 1; }
    .step-item.done { opacity: .7; }
    .step-num { width: 24px; height: 24px; border: 2px solid rgba(255,255,255,.5); border-radius: 50%;
      display: flex; align-items: center; justify-content: center; font-size: .75rem; font-weight: 700; }
    .step-item.active .step-num { border-color: #C9982E; background: #C9982E; }
    .step-item.done .step-num { border-color: white; background: rgba(255,255,255,.2); }
    .step-line { flex: 1; height: 1px; background: rgba(255,255,255,.2); }

    /* Panneau droit */
    .right-panel {
      flex: 1;
      display: flex;
      align-items: center;
      justify-content: center;
      padding: 2rem;
      background: #f9fafb;
      overflow-y: auto;
    }

    .form-card {
      background: white;
      border-radius: 1.25rem;
      box-shadow: 0 4px 24px rgba(0,0,0,.08);
      padding: 2.5rem;
      width: 100%;
      max-width: 480px;
    }

    .step-content { display: flex; flex-direction: column; gap: 1.25rem; }
    .step-content h2 { font-size: 1.5rem; font-weight: 700; color: #111827; margin: 0; }
    .subtitle { color: #6b7280; font-size: .9rem; margin: 0; }

    .back-btn { background: none; border: none; color: #6b7280; cursor: pointer; font-size: .9rem;
      padding: 0; text-align: left; width: fit-content; }
    .back-btn:hover { color: #0F4C81; }

    /* Choix de rôle */
    .role-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 1rem; }
    .role-card {
      border: 2px solid #e5e7eb; border-radius: .875rem; padding: 1.25rem;
      display: flex; flex-direction: column; align-items: center; gap: .5rem;
      cursor: pointer; background: white; transition: all .2s; text-align: center;
    }
    .role-card svg { width: 36px; height: 36px; color: #9ca3af; }
    .role-card strong { color: #111827; font-size: .95rem; }
    .role-card span { color: #6b7280; font-size: .8rem; line-height: 1.4; }
    .role-card:hover { border-color: #0F4C81; }
    .role-card.selected { border-color: #0F4C81; background: #f0f7ff; }
    .role-card.selected svg { color: #0F4C81; }

    /* Formulaire */
    .form-fields { display: flex; flex-direction: column; gap: 1rem; }
    .field-row { display: grid; grid-template-columns: 1fr 1fr; gap: 1rem; }
    .field { display: flex; flex-direction: column; gap: .375rem; }
    .field label { font-size: .85rem; font-weight: 500; color: #374151; }
    .field label small { font-weight: 400; color: #9ca3af; }
    .field input, .field select {
      border: 1.5px solid #d1d5db; border-radius: .5rem; padding: .625rem .875rem;
      font-size: .95rem; outline: none; transition: border-color .2s; width: 100%; box-sizing: border-box;
    }
    .field input:focus, .field select:focus { border-color: #0F4C81; }
    .error { color: #ef4444; font-size: .78rem; }

    /* Upload CNI */
    .cni-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 1rem; }
    .upload-zone {
      border: 2px dashed #d1d5db; border-radius: .875rem; padding: 1.5rem 1rem;
      display: flex; flex-direction: column; align-items: center; justify-content: center;
      gap: .5rem; cursor: pointer; transition: all .2s; text-align: center; min-height: 140px;
    }
    .upload-zone svg { width: 32px; height: 32px; color: #9ca3af; }
    .upload-zone strong { font-size: .9rem; color: #374151; }
    .upload-zone span { font-size: .78rem; color: #9ca3af; }
    .upload-zone:hover { border-color: #0F4C81; background: #f0f7ff; }
    .upload-zone.has-file { border-color: #10b981; background: #f0fdf4; border-style: solid; }
    .file-preview { display: flex; flex-direction: column; align-items: center; gap: .5rem; }
    .file-preview svg { width: 28px; height: 28px; color: #10b981; }
    .file-preview span { font-size: .78rem; color: #374151; word-break: break-all; }

    /* Bouton principal */
    .btn-primary {
      background: #0F4C81; color: white; border: none; border-radius: .625rem;
      padding: .75rem 1.5rem; font-size: .95rem; font-weight: 600; cursor: pointer;
      display: flex; align-items: center; justify-content: center; gap: .5rem;
      width: 100%; transition: background .2s;
    }
    .btn-primary:hover:not(:disabled) { background: #0A2650; }
    .btn-primary:disabled { opacity: .5; cursor: not-allowed; }
    .btn-primary svg { width: 18px; height: 18px; }

    .spinner { animation: spin 1s linear infinite; }
    @keyframes spin { from { transform: rotate(0deg); } to { transform: rotate(360deg); } }

    .login-link { text-align: center; font-size: .85rem; color: #6b7280; }
    .login-link a { color: #0F4C81; font-weight: 600; text-decoration: none; }
    .login-link a:hover { text-decoration: underline; }

    .error-banner {
      background: #fef2f2; border: 1px solid #fecaca; border-radius: .5rem;
      padding: .75rem 1rem; color: #dc2626; font-size: .875rem;
    }

    /* Succès */
    .success-content { text-align: center; align-items: center; padding: 1rem 0; }
    .success-icon svg { width: 64px; height: 64px; color: #10b981; }
    .success-content h2 { font-size: 1.75rem; }
    .success-content p { color: #6b7280; max-width: 340px; }
    .info-note { background: #eff6ff; border-radius: .5rem; padding: .75rem; color: #1d4ed8 !important; font-size: .85rem !important; }
  `],
})
export class RegisterComponent {
  step = signal<Step>('role');
  selectedRole = signal<Role | null>(null);
  isLoading = signal(false);
  errorMessage = signal('');

  cniRecto: File | null = null;
  cniVerso: File | null = null;
  refDocs: File[] = [];

  infoForm: FormGroup;

  constructor(
    private fb: FormBuilder,
    private authService: AuthService,
    private router: Router,
    private cdr: ChangeDetectorRef,
  ) {
    this.infoForm = this.fb.group({
      firstName:        ['', Validators.required],
      lastName:         ['', Validators.required],
      email:            ['', [Validators.required, Validators.email]],
      password:         ['', [Validators.required, Validators.minLength(6)]],
      residenceCountry: [''],
    });
  }

  stepIndex(): number {
    const map: Record<Step, number> = { role: 0, info: 1, cni: 2, success: 3 };
    return map[this.step()];
  }

  selectRole(role: Role): void {
    this.selectedRole.set(role);
    const ctrl = this.infoForm.get('residenceCountry')!;
    if (role === 'OWNER') {
      ctrl.setValidators(Validators.required);
    } else {
      ctrl.clearValidators();
    }
    ctrl.updateValueAndValidity();
  }

  goToInfo(): void {
    if (this.selectedRole()) this.step.set('info');
  }

  goToCni(): void {
    if (this.infoForm.valid) this.step.set('cni');
    else this.infoForm.markAllAsTouched();
  }

  goBack(): void {
    this.step.set('role');
  }

  triggerInput(el: HTMLInputElement): void {
    el.click();
  }

  onFile(event: Event, side: 'recto' | 'verso'): void {
    const file = (event.target as HTMLInputElement).files?.[0];
    if (!file) return;
    if (side === 'recto') this.cniRecto = file;
    else this.cniVerso = file;
    this.cdr.markForCheck();
  }

  onRefDocs(event: Event): void {
    const files = (event.target as HTMLInputElement).files;
    if (files) this.refDocs = Array.from(files).slice(0, 5);
  }

  submit(): void {
    if (!this.cniRecto || !this.cniVerso || !this.selectedRole()) return;
    this.isLoading.set(true);
    this.errorMessage.set('');

    const v = this.infoForm.value;
    const role = this.selectedRole()!;

    const obs$ = role === 'OWNER'
      ? this.authService.signupOwner({
          email: v.email,
          password: v.password,
          firstName: v.firstName,
          lastName: v.lastName,
          residenceCountry: v.residenceCountry,
          cniRecto: this.cniRecto,
          cniVerso: this.cniVerso,
        })
      : this.authService.signupManager({
          email: v.email,
          password: v.password,
          firstName: v.firstName,
          lastName: v.lastName,
          cniRecto: this.cniRecto,
          cniVerso: this.cniVerso,
          referenceDocuments: this.refDocs.length ? this.refDocs : undefined,
        });

    obs$.subscribe({
      next: () => {
        this.isLoading.set(false);
        this.step.set('success');
      },
      error: (err: any) => {
        this.isLoading.set(false);
        this.errorMessage.set(err.error?.message || 'Une erreur est survenue lors de la création du compte.');
        this.cdr.markForCheck();
      },
    });
  }
}

// apps/frontend/src/app/auth/register/page.tsx
'use client';

import { useEffect, useRef, useState, type ChangeEvent } from 'react';
import Link from 'next/link';
import { PHONE_PREFIXES, matchPrefix, phoneLengthError, phoneIsValid, type PhonePrefix } from '@/lib/phone-prefixes';
import { signupOwner, signupManager } from '@/lib/signup';
import { ApiError } from '@/lib/auth-context';
import './page.css';

type Role = 'OWNER' | 'MANAGER';
type Step = 'role' | 'info' | 'cni' | 'success';

interface InfoForm {
  firstName: string;
  lastName: string;
  email: string;
  password: string;
  phone: string;
  city: string;
  residenceCountry: string;
}

const EMPTY_INFO: InfoForm = { firstName: '', lastName: '', email: '', password: '', phone: '', city: '', residenceCountry: '' };

export default function RegisterPage() {
  const [step, setStep] = useState<Step>('role');
  const [selectedRole, setSelectedRole] = useState<Role | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [errorMessage, setErrorMessage] = useState('');

  const [info, setInfo] = useState<InfoForm>(EMPTY_INFO);
  const [touched, setTouched] = useState<Partial<Record<keyof InfoForm, boolean>>>({});

  const [detectedCountry, setDetectedCountry] = useState<PhonePrefix | null>(null);
  const [showCountryPicker, setShowCountryPicker] = useState(false);
  const [countrySearch, setCountrySearch] = useState('');
  const phoneWrapRef = useRef<HTMLDivElement>(null);

  const [cniRecto, setCniRecto] = useState<File | null>(null);
  const [cniVerso, setCniVerso] = useState<File | null>(null);
  const [refDocs, setRefDocs] = useState<File[]>([]);
  const rectoInputRef = useRef<HTMLInputElement>(null);
  const versoInputRef = useRef<HTMLInputElement>(null);

  const stepIndex = { role: 0, info: 1, cni: 2, success: 3 }[step];

  // Ferme le sélecteur de pays au clic extérieur / touche Échap
  useEffect(() => {
    function onDocClick(e: MouseEvent) {
      if (!showCountryPicker) return;
      if (phoneWrapRef.current && !phoneWrapRef.current.contains(e.target as Node)) {
        setShowCountryPicker(false);
      }
    }
    function onKeyDown(e: KeyboardEvent) {
      if (e.key === 'Escape') setShowCountryPicker(false);
    }
    document.addEventListener('click', onDocClick);
    document.addEventListener('keydown', onKeyDown);
    return () => {
      document.removeEventListener('click', onDocClick);
      document.removeEventListener('keydown', onKeyDown);
    };
  }, [showCountryPicker]);

  function setField<K extends keyof InfoForm>(key: K, value: InfoForm[K]) {
    setInfo((f) => ({ ...f, [key]: value }));
  }
  function markTouched(key: keyof InfoForm) {
    setTouched((t) => ({ ...t, [key]: true }));
  }

  const firstNameInvalid = touched.firstName && !info.firstName.trim();
  const lastNameInvalid = touched.lastName && !info.lastName.trim();
  const emailInvalid = touched.email && !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(info.email);
  const passwordInvalid = touched.password && info.password.length < 6;
  const phoneErr = phoneLengthError(info.phone);
  const phoneInvalid = touched.phone && !phoneIsValid(info.phone);
  const cityInvalid = touched.city && !info.city.trim();

  const infoFormValid =
    !!info.firstName.trim() && !!info.lastName.trim() &&
    /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(info.email) &&
    info.password.length >= 6 &&
    phoneIsValid(info.phone) &&
    !!info.city.trim();

  const filteredPrefixes = (() => {
    const q = countrySearch.trim().toLowerCase();
    if (!q) return PHONE_PREFIXES;
    return PHONE_PREFIXES.filter(
      (p) => p.name.toLowerCase().includes(q) || p.code.includes(q) || p.country.toLowerCase().includes(q),
    );
  })();

  function onPhoneInput(value: string) {
    setField('phone', value);
    const match = matchPrefix(value.trim());
    setDetectedCountry(match);
    if (match) setField('residenceCountry', match.country);
  }

  function toggleCountryPicker(e: React.MouseEvent) {
    e.stopPropagation();
    setShowCountryPicker((v) => !v);
    setCountrySearch('');
  }

  function selectCountry(p: PhonePrefix) {
    const raw = info.phone.trim();
    const localPart = detectedCountry && raw.startsWith(detectedCountry.code)
      ? raw.slice(detectedCountry.code.length).trim()
      : raw.replace(/^\+/, '').replace(/\D/g, '');
    setField('phone', localPart ? `${p.code} ${localPart}` : `${p.code} `);
    setField('residenceCountry', p.country);
    setDetectedCountry(p);
    setShowCountryPicker(false);
    setCountrySearch('');
  }

  function goToInfo() {
    if (selectedRole) setStep('info');
  }

  function goToCni(e: React.FormEvent) {
    e.preventDefault();
    if (infoFormValid) {
      setStep('cni');
    } else {
      setTouched({ firstName: true, lastName: true, email: true, password: true, phone: true, city: true });
    }
  }

  function onFile(e: ChangeEvent<HTMLInputElement>, side: 'recto' | 'verso') {
    const file = e.target.files?.[0];
    if (!file) return;
    if (side === 'recto') setCniRecto(file);
    else setCniVerso(file);
  }

  function onRefDocs(e: ChangeEvent<HTMLInputElement>) {
    const files = e.target.files;
    if (files) setRefDocs(Array.from(files).slice(0, 5));
  }

  async function submit() {
    if (!cniRecto || !cniVerso || !selectedRole) return;
    setIsLoading(true);
    setErrorMessage('');

    const phone = info.phone.replace(/\s+/g, '');

    try {
      if (selectedRole === 'OWNER') {
        await signupOwner({
          email: info.email,
          password: info.password,
          firstName: info.firstName,
          lastName: info.lastName,
          phone,
          city: info.city,
          residenceCountry: info.residenceCountry || 'TG',
          cniRecto,
          cniVerso,
        });
      } else {
        await signupManager({
          email: info.email,
          password: info.password,
          firstName: info.firstName,
          lastName: info.lastName,
          phone,
          city: info.city,
          cniRecto,
          cniVerso,
          referenceDocuments: refDocs.length ? refDocs : undefined,
        });
      }
      setIsLoading(false);
      setStep('success');
    } catch (err) {
      setIsLoading(false);
      setErrorMessage(err instanceof ApiError ? err.message : 'Une erreur est survenue lors de la création du compte.');
    }
  }

  return (
    <div className="register-page">
      {/* Panneau gauche */}
      <div className="left-panel">
        <div className="left-content">
          <Link href="/" className="lp-logo">
            <img src="/warah-icon.png" alt="" className="lp-logo-icon" />
            WARAH
          </Link>
          <h1>L&apos;immobilier togolais<br />dans votre poche</h1>
          <ul className="features">
            <li>Gérez vos biens à distance</li>
            <li>Encaissez via T-Money &amp; Flooz</li>
            <li>Statistiques en temps réel</li>
            <li>Vérification CNI sécurisée</li>
          </ul>
          <div className="steps-indicator">
            <div className={`step-item${step === 'role' ? ' active' : ''}${stepIndex > 0 ? ' done' : ''}`}>
              <span className="step-num">1</span><span>Rôle</span>
            </div>
            <div className="step-line" />
            <div className={`step-item${step === 'info' ? ' active' : ''}${stepIndex > 1 ? ' done' : ''}`}>
              <span className="step-num">2</span><span>Informations</span>
            </div>
            <div className="step-line" />
            <div className={`step-item${step === 'cni' ? ' active' : ''}${stepIndex > 2 ? ' done' : ''}`}>
              <span className="step-num">3</span><span>Pièce d&apos;identité</span>
            </div>
          </div>
        </div>
      </div>

      {/* Panneau droit */}
      <div className="right-panel">
        <div className="form-card">
          {/* ÉTAPE 1 : Choix du rôle */}
          {step === 'role' && (
            <div className="step-content">
              <h2>Créer votre compte</h2>
              <p className="subtitle">Je suis…</p>
              <div className="role-grid">
                <button type="button" className={`role-card${selectedRole === 'OWNER' ? ' selected' : ''}`} onClick={() => setSelectedRole('OWNER')}>
                  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5">
                    <path d="M3 9l9-7 9 7v11a2 2 0 01-2 2H5a2 2 0 01-2-2z"/>
                    <polyline points="9 22 9 12 15 12 15 22"/>
                  </svg>
                  <strong>Propriétaire</strong>
                  <span>Je possède des biens immobiliers au Togo</span>
                </button>
                <button type="button" className={`role-card${selectedRole === 'MANAGER' ? ' selected' : ''}`} onClick={() => setSelectedRole('MANAGER')}>
                  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5">
                    <path d="M17 21v-2a4 4 0 00-4-4H5a4 4 0 00-4 4v2"/>
                    <circle cx="9" cy="7" r="4"/>
                    <path d="M23 21v-2a4 4 0 00-3-3.87M16 3.13a4 4 0 010 7.75"/>
                  </svg>
                  <strong>Gestionnaire</strong>
                  <span>Je gère des biens pour le compte de propriétaires</span>
                </button>
              </div>
              <button className="btn-primary" disabled={!selectedRole} onClick={goToInfo}>
                Continuer
                <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M5 12h14M12 5l7 7-7 7"/></svg>
              </button>
              <p className="login-link">Déjà un compte ? <Link href="/auth/login">Se connecter</Link></p>
            </div>
          )}

          {/* ÉTAPE 2 : Informations personnelles */}
          {step === 'info' && (
            <div className="step-content">
              <button className="back-btn" onClick={() => setStep('role')}>← Retour</button>
              <h2>Vos informations</h2>
              <p className="subtitle">{selectedRole === 'OWNER' ? 'Compte propriétaire' : 'Compte gestionnaire immobilier'}</p>
              <form onSubmit={goToCni} className="form-fields">
                <div className="field-row">
                  <div className="field">
                    <label>Prénom *</label>
                    <input type="text" placeholder="Kofi" value={info.firstName} onChange={(e) => setField('firstName', e.target.value)} onBlur={() => markTouched('firstName')} />
                    {firstNameInvalid && <span className="error">Prénom requis</span>}
                  </div>
                  <div className="field">
                    <label>Nom *</label>
                    <input type="text" placeholder="Mensah" value={info.lastName} onChange={(e) => setField('lastName', e.target.value)} onBlur={() => markTouched('lastName')} />
                    {lastNameInvalid && <span className="error">Nom requis</span>}
                  </div>
                </div>
                <div className="field">
                  <label>Email *</label>
                  <input type="email" placeholder="kofi@exemple.com" value={info.email} onChange={(e) => setField('email', e.target.value)} onBlur={() => markTouched('email')} />
                  {emailInvalid && <span className="error">Email valide requis</span>}
                </div>
                <div className="field">
                  <label>Mot de passe * <small>(min 6 caractères)</small></label>
                  <input type="password" placeholder="••••••••" value={info.password} onChange={(e) => setField('password', e.target.value)} onBlur={() => markTouched('password')} />
                  {passwordInvalid && <span className="error">Minimum 6 caractères</span>}
                </div>

                {/* Téléphone avec sélecteur de pays */}
                <div className="field">
                  <label>Téléphone *</label>
                  <div className={`phone-wrap${showCountryPicker ? ' open' : ''}`} ref={phoneWrapRef}>
                    <button type="button" className="phone-prefix" aria-haspopup="listbox" aria-expanded={showCountryPicker} onClick={toggleCountryPicker}>
                      {detectedCountry ? (
                        <img src={`https://flagcdn.com/w40/${detectedCountry.country.toLowerCase()}.png`} alt={detectedCountry.name} className="flag-img" title={`${detectedCountry.name} ${detectedCountry.code}`} />
                      ) : (
                        <svg width="18" height="18" fill="none" stroke="#9ca3af" strokeWidth="1.8" viewBox="0 0 24 24">
                          <circle cx="12" cy="12" r="10"/>
                          <line x1="2" y1="12" x2="22" y2="12"/>
                          <path d="M12 2a15.3 15.3 0 010 20M12 2a15.3 15.3 0 000 20"/>
                        </svg>
                      )}
                      <svg className="chevron" width="10" height="10" viewBox="0 0 12 12" fill="none" stroke="currentColor" strokeWidth="1.6"><path d="M3 4.5l3 3 3-3"/></svg>
                    </button>
                    <input
                      type="tel"
                      placeholder="+228 90 12 34 56"
                      className="phone-input"
                      value={info.phone}
                      onChange={(e) => onPhoneInput(e.target.value)}
                      onFocus={() => setShowCountryPicker(false)}
                      onBlur={() => markTouched('phone')}
                    />

                    {showCountryPicker && (
                      <div className="country-dropdown" role="listbox">
                        <input type="text" className="country-search" placeholder="Rechercher un pays…" value={countrySearch} onChange={(e) => setCountrySearch(e.target.value)} autoFocus />
                        <div className="country-list">
                          {filteredPrefixes.length === 0 ? (
                            <div className="country-empty">Aucun pays trouvé</div>
                          ) : (
                            filteredPrefixes.map((p) => (
                              <button key={p.country} type="button" className={`country-item${detectedCountry?.country === p.country ? ' active' : ''}`} onClick={() => selectCountry(p)}>
                                <img src={`https://flagcdn.com/w40/${p.country.toLowerCase()}.png`} alt={p.name} className="flag-img" />
                                <span className="country-name">{p.name}</span>
                                <span className="country-code">{p.code}</span>
                              </button>
                            ))
                          )}
                        </div>
                      </div>
                    )}
                  </div>
                  {touched.phone && phoneErr ? (
                    <span className="error">
                      {phoneErr.country} : le numéro doit comporter {phoneErr.expected} chiffres après l&apos;indicatif (actuellement {phoneErr.actual})
                    </span>
                  ) : phoneInvalid ? (
                    <span className="error">Numéro de téléphone invalide (ex : +22890123456)</span>
                  ) : null}
                </div>

                <div className="field">
                  <label>Ville de résidence *</label>
                  <input type="text" placeholder="Lomé" value={info.city} onChange={(e) => setField('city', e.target.value)} onBlur={() => markTouched('city')} />
                  {cityInvalid && <span className="error">Ville requise</span>}
                </div>

                <button type="submit" className="btn-primary" disabled={!infoFormValid}>
                  Continuer
                  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M5 12h14M12 5l7 7-7 7"/></svg>
                </button>
              </form>
            </div>
          )}

          {/* ÉTAPE 3 : CNI upload */}
          {step === 'cni' && (
            <div className="step-content">
              <button className="back-btn" onClick={() => setStep('info')}>← Retour</button>
              <h2>Pièce d&apos;identité</h2>
              <p className="subtitle">CNI en cours de validité — recto et verso (JPG/PNG, max 5 Mo)</p>

              {errorMessage && <div className="error-banner">{errorMessage}</div>}

              <div className="cni-grid">
                <button type="button" className={`upload-zone${cniRecto ? ' has-file' : ''}`} onClick={() => rectoInputRef.current?.click()}>
                  <input ref={rectoInputRef} type="file" accept="image/jpeg,image/png,image/webp" onChange={(e) => onFile(e, 'recto')} style={{ display: 'none' }} />
                  {cniRecto ? (
                    <span className="file-preview">
                      <span className="file-preview-ic"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M9 11l3 3L22 4"/><path d="M21 12v7a2 2 0 01-2 2H5a2 2 0 01-2-2V5a2 2 0 012-2h11"/></svg></span>
                      <span>{cniRecto.name}</span>
                    </span>
                  ) : (
                    <>
                      <span className="upload-ic"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5"><path d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-8l-4-4m0 0L8 8m4-4v12"/></svg></span>
                      <strong>CNI Recto</strong>
                      <span>Cliquer pour sélectionner</span>
                    </>
                  )}
                </button>
                <button type="button" className={`upload-zone${cniVerso ? ' has-file' : ''}`} onClick={() => versoInputRef.current?.click()}>
                  <input ref={versoInputRef} type="file" accept="image/jpeg,image/png,image/webp" onChange={(e) => onFile(e, 'verso')} style={{ display: 'none' }} />
                  {cniVerso ? (
                    <span className="file-preview">
                      <span className="file-preview-ic"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M9 11l3 3L22 4"/><path d="M21 12v7a2 2 0 01-2 2H5a2 2 0 01-2-2V5a2 2 0 012-2h11"/></svg></span>
                      <span>{cniVerso.name}</span>
                    </span>
                  ) : (
                    <>
                      <span className="upload-ic"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5"><path d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-8l-4-4m0 0L8 8m4-4v12"/></svg></span>
                      <strong>CNI Verso</strong>
                      <span>Cliquer pour sélectionner</span>
                    </>
                  )}
                </button>
              </div>

              {selectedRole === 'MANAGER' && (
                <div className="field" style={{ marginTop: '1rem' }}>
                  <label>Références professionnelles <small>(optionnel — max 5 fichiers)</small></label>
                  <input type="file" accept="image/*,.pdf" multiple onChange={onRefDocs} style={{ width: '100%', padding: '.5rem', border: '1px dashed #d1d5db', borderRadius: '.5rem', cursor: 'pointer' }} />
                  {refDocs.length > 0 && <span style={{ fontSize: 13, color: '#6b7280' }}>{refDocs.length} fichier(s) sélectionné(s)</span>}
                </div>
              )}

              <button className="btn-primary" disabled={!cniRecto || !cniVerso || isLoading} onClick={submit}>
                {isLoading ? (
                  <>
                    <svg className="spinner" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><circle cx="12" cy="12" r="10" opacity=".25"/><path d="M12 2a10 10 0 0110 10" opacity=".75"/></svg>
                    Création en cours…
                  </>
                ) : (
                  'Créer mon compte'
                )}
              </button>
            </div>
          )}

          {/* ÉTAPE 4 : Succès */}
          {step === 'success' && (
            <div className="step-content success-content">
              <div className="success-icon">
                <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5">
                  <path d="M9 12l2 2 4-4"/>
                </svg>
              </div>
              <h2>Compte créé !</h2>
              <p>Votre compte a été créé avec succès. Votre pièce d&apos;identité est en cours de vérification (sous 24h).</p>
              <p className="info-note">Vous pouvez vous connecter dès maintenant. Certaines fonctionnalités seront disponibles après validation de votre CNI.</p>
              <Link href="/auth/login" className="btn-primary">Se connecter</Link>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
